#!/bin/sh

package=$(echo $TEST_DIR | sed 's/\.\/packages\///')
version=$(grep -m1 version package.json | awk -F: '{ print $2 }' | sed 's/[", ]//g')

if [ "$CIRCLE_BRANCH" = "master" ]; then
  # npm publish is an idempotent action
  tempLog=$(mktemp)

  echo "Trying to publish..."
  npm publish > ${tempLog} 2>&1

  if [ $? -eq 0 ]; then
    curl -H "Content-Type: application/json" \
         -X POST \
         -d "{\"text\":\"A new version *$version* of *$package* package has been just published. <https://www.npmjs.com/package/@blueberry/4finance-$package>\",\"username\":\"circle-ci\",\"icon_emoji\":\":tada:\"}" \
         https://hooks.slack.com/services/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

    echo "Successfully published!"
  else
    grep -q "You cannot publish over the previously published version" npm-debug.log
    grepStatus=$?

    if [ $grepStatus -eq 0 ]; then
      echo "Already published."
    else
      cat ${tempLog}
    fi

    rm -f ${tempLog}
    exit $grepStatus
  fi

  rm -f ${tempLog}
fi
